version: "3.8"

services:
  survie01:
    environment:
      INIT_MEMORY: '4G'
      MAX_MEMORY: '8G'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8G'

  proxy:
    environment:
      INIT_MEMORY: '128M'
      MAX_MEMORY: '2G'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'
