version: "3.8"

services:
  survie:
    image: itzg/minecraft-server:latest
    environment:
      EULA: "TRUE"
      TYPE: "PUFFERFISH"
      ONLINE_MODE: "FALSE"
    volumes:
      - "./survie:/data"
    stdin_open: true
    tty: true
    restart: unless-stopped

  proxy:
    image: itzg/bungeecord
    ports:
      - "25565:25566"
    volumes:
      - "./proxy:/server"
    environment:
      ENABLE_RCON: "TRUE"
      TYPE: WATERFALL
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
      # define an optional prefix for your env variables you want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
    tty: true
    stdin_open: true
    restart: unless-stopped

  mariadb:
    image: mariadb
    user: "1000:1000"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./mariadb:/var/lib/mysql"
      - "./backup/mariadb:/backup"
    restart: unless-stopped

  adminer:
    image: adminer:latest
    depends_on:
        - mariadb
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DEFAULT_HOST: mariadb
      ADMINER_DEFAULT_USERNAME: ${DB_USER}
      ADMINER_DEFAULT_PASSWORD: ${DB_PASSWORD}
      ADMINER_DEFAULT_DATABASE: ${DB_NAME}
    restart: unless-stopped
    ports:
      - 23283:8080

  redis:
    image: redis:6.2
    user: "1000:1000"
    volumes:
      - "./redis:/data"
    command: >
      --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
